
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWindOracleLibrary.Models;

namespace NorthWindOracleLibrary.Data.Configurations;

public partial class CustomersConfiguration : IEntityTypeConfiguration<Customers>
{
    public void Configure(EntityTypeBuilder<Customers> entity)
    {
        entity.HasKey(e => e.CustomerId);

        entity.HasIndex(e => e.City, "IDX_CUSTOMERS_CITY");

        entity.HasIndex(e => e.CompanyName, "IDX_CUSTOMERS_COMPANY_NAME");

        entity.HasIndex(e => e.PostalCode, "IDX_CUSTOMERS_POSTAL_CODE");

        entity.HasIndex(e => e.Region, "IDX_CUSTOMERS_REGION");

        entity.HasIndex(e => e.CustomerCode, "UIDX_CUSTOMERS_CODE").IsUnique();

        entity.Property(e => e.CustomerId)
            .HasPrecision(9)
            .ValueGeneratedNever();
        entity.Property(e => e.Address)
            .HasMaxLength(60)
            .IsUnicode(false);
        entity.Property(e => e.City)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.CompanyName)
            .IsRequired()
            .HasMaxLength(40)
            .IsUnicode(false);
        entity.Property(e => e.ContactName)
            .HasMaxLength(30)
            .IsUnicode(false);
        entity.Property(e => e.ContactTitle)
            .HasMaxLength(30)
            .IsUnicode(false);
        entity.Property(e => e.Country)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.CustomerCode)
            .IsRequired()
            .HasMaxLength(5)
            .IsUnicode(false);
        entity.Property(e => e.FAX)
            .HasMaxLength(24)
            .IsUnicode(false);
        entity.Property(e => e.Phone)
            .HasMaxLength(24)
            .IsUnicode(false);
        entity.Property(e => e.PostalCode)
            .HasMaxLength(10)
            .IsUnicode(false);
        entity.Property(e => e.Region)
            .HasMaxLength(15)
            .IsUnicode(false);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Customers> entity);
}