
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWindOracleLibrary.Models;

namespace NorthWindOracleLibrary.Data.Configurations;

public partial class OrdersConfiguration : IEntityTypeConfiguration<Orders>
{
    public void Configure(EntityTypeBuilder<Orders> entity)
    {
        entity.HasKey(e => e.OrderId);

        entity.HasIndex(e => e.CustomerId, "IDX_ORDERS_CUSTOMER_ID");

        entity.HasIndex(e => e.EmployeeId, "IDX_ORDERS_EMPLOYEE_ID");

        entity.HasIndex(e => e.OrderDate, "IDX_ORDERS_ORDER_DATE");

        entity.HasIndex(e => e.ShippedDate, "IDX_ORDERS_SHIPPED_DATE");

        entity.HasIndex(e => e.ShipVia, "IDX_ORDERS_SHIPPER_ID");

        entity.HasIndex(e => e.ShipPostalCode, "IDX_ORDERS_SHIP_POSTAL_CODE");

        entity.Property(e => e.OrderId)
            .HasPrecision(9)
            .ValueGeneratedNever();
        entity.Property(e => e.CustomerId).HasPrecision(9);
        entity.Property(e => e.EmployeeId).HasPrecision(9);
        entity.Property(e => e.Freight)
            .HasDefaultValueSql("0")
            .HasColumnType("NUMBER(10,2)");
        entity.Property(e => e.OrderDate).HasColumnType("DATE");
        entity.Property(e => e.RequiredDate).HasColumnType("DATE");
        entity.Property(e => e.ShippedDate).HasColumnType("DATE");
        entity.Property(e => e.ShipAddress)
            .HasMaxLength(60)
            .IsUnicode(false);
        entity.Property(e => e.ShipCity)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.ShippedCountry)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.ShipName)
            .HasMaxLength(40)
            .IsUnicode(false);
        entity.Property(e => e.ShipPostalCode)
            .HasMaxLength(10)
            .IsUnicode(false);
        entity.Property(e => e.ShipRegion)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.ShipVia).HasPrecision(9);

        entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
            .HasForeignKey(d => d.CustomerId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_CUSTOMER_ID");

        entity.HasOne(d => d.Employee).WithMany(p => p.ORDERS)
            .HasForeignKey(d => d.EmployeeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_EMPLOYEE_ID");

        entity.HasOne(d => d.ShipViaNavigation).WithMany(p => p.Orders)
            .HasForeignKey(d => d.ShipVia)
            .HasConstraintName("FK_SHIPPER_ID");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Orders> entity);
}