
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWindOracleLibrary.Models;

namespace NorthWindOracleLibrary.Data.Configurations;

public partial class OrderDetailsConfiguration : IEntityTypeConfiguration<OrderDetails>
{
    public void Configure(EntityTypeBuilder<OrderDetails> entity)
    {
        entity.HasKey(e => new { ORDER_ID = e.OrderId, PRODUCT_ID = e.ProductId });

        entity.HasIndex(e => e.OrderId, "IDX_ORDER_DETAILS_ORDER_ID");

        entity.HasIndex(e => e.ProductId, "IDX_ORDER_DETAILS_PRODUCT_ID");

        entity.Property(e => e.OrderId).HasPrecision(9);
        entity.Property(e => e.ProductId).HasPrecision(9);
        entity.Property(e => e.DISCOUNT)
            .HasDefaultValueSql("0\n   ")
            .HasColumnType("NUMBER(4,2)");
        entity.Property(e => e.Quantity)
            .HasPrecision(9)
            .HasDefaultValueSql("1");
        entity.Property(e => e.UnitPrice)
            .HasDefaultValueSql("0")
            .HasColumnType("NUMBER(10,2)");

        entity.HasOne(d => d.Order).WithMany(p => p.ORDER_DETAILS)
            .HasForeignKey(d => d.OrderId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ORDER_ID");

        entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
            .HasForeignKey(d => d.ProductId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PRODUCT_ID");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<OrderDetails> entity);
}