
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;


namespace NorthWindOracleLibrary.Models;

[Table("CUSTOMERS")]
public partial class Customers
{
    [Column("CUSTOMER_ID")]
    public int CustomerId { get; set; }

    [Column("CUSTOMER_CODE")]
    public string CustomerCode { get; set; }

    [Column("COMPANY_NAME")]
    [Display(Name = "Company")]
    public string CompanyName { get; set; }

    [Column("CONTACT_NAME")]
    [Display(Name = "Contact")]
    public string ContactName { get; set; }

    [Column("CONTACT_TITLE")]
    [Display(Name = "Title")]
    public string ContactTitle { get; set; }

    [Column("ADDRESS")]
    public string Address { get; set; }

    [Column("CITY")]
    public string City { get; set; }

    [Column("REGION")]
    public string Region { get; set; }

    [Column("POSTAL_CODE")]
    public string PostalCode { get; set; }

    [Column("COUNTRY")]
    public string Country { get; set; }

    [Column("PHONE")]
    [Display(Name = "Company main phone number")]
    public string Phone { get; set; }

    public string FAX { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}