
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWindOracleLibrary.Models;

[Table("EMPLOYEES")]
public partial class Employees
{
    [Column("EMPLOYEE_ID")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public int EmployeeId { get; set; }

    [Column("LASTNAME")]
    [Display(Name = "Last")]
    public string LastName { get; set; }

    [Column("FIRSTNAME")]
    [Display(Name = "First")]
    public string FirstName { get; set; }

    public string FullName => $"{FirstName} {LastName}";

    [Column("TITLE")]
    public string Title { get; set; }

    [Column("TITLE_OF_COURTESY")]
    public string CourtesyTitle { get; set; }

    [Column("BIRTHDATE")]
    public DateTime? BirthDate { get; set; }

    public DateOnly BirthDay => DateOnly.FromDateTime(BirthDate.Value);

    [Column("HIREDATE")]
    public DateTime? HiredDate { get; set; }

    [Column("ADDRESS")]
    public string Address { get; set; }

    [Column("CITY")]
    public string City { get; set; }

    [Column("REGION")]
    public string Region { get; set; }

    [Column("POSTAL_CODE")]
    public string PostalCode { get; set; }

    [Column("COUNTRY")]
    public string Country { get; set; }

    [Column("HOME_PHONE")]
    public string HomePhone { get; set; }

    [Column("EXTENSION")]
    public string Extension { get; set; }

    [Column("PHOTO")]
    public string Photo { get; set; }

    [Column("NOTES")]
    public string Notes { get; set; }

    [Column("REPORTS_TO")]
    public int? ReportsTo { get; set; }

    public override string ToString() => $"{FirstName} {LastName}";


    public virtual ICollection<Employees> InverseReportsToNavigation { get; set; } = new List<Employees>();

    public virtual ICollection<Orders> ORDERS { get; set; } = new List<Orders>();

    public virtual Employees ReportsToNavigation { get; set; }
}