
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWindOracleLibrary.Models;

[Table("ORDER_DETAILS")]
public partial class OrderDetails
{
    [Column("ORDER_ID")]
    public int OrderId { get; set; }

    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Column("UNIT_PRICE")]
    public decimal UnitPrice { get; set; }

    [Column("QUANTITY")]
    public int Quantity { get; set; }

    public decimal DISCOUNT { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Products Product { get; set; }
}