
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWindOracleLibrary.Models;

[Table("ORDERS")]
public partial class Orders
{
    [Column("ORDER_ID")]
    public int OrderId { get; set; }

    [Column("CUSTOMER_ID")]
    public int CustomerId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int EmployeeId { get; set; }

    [Column("ORDER_DATE")]
    public DateTime OrderDate { get; set; }

    [Column("REQUIRED_DATE")]
    public DateTime? RequiredDate { get; set; }

    [Column("SHIPPED_DATE")]
    public DateTime? ShippedDate { get; set; }

    [Column("SHIP_VIA")]
    public int? ShipVia { get; set; }

    [Column("FREIGHT")]
    public decimal? Freight { get; set; }

    [Column("SHIP_NAME")]
    public string ShipName { get; set; }

    [Column("SHIP_ADDRESS")]
    public string ShipAddress { get; set; }

    [Column("SHIP_CITY")]
    public string ShipCity { get; set; }

    [Column("SHIP_REGION")]
    public string ShipRegion { get; set; }

    [Column("SHIP_POSTAL_CODE")]
    public string ShipPostalCode { get; set; }

    [Column("SHIP_COUNTRY")]
    public string ShippedCountry { get; set; }

    public virtual Customers Customer { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual Shippers ShipViaNavigation { get; set; }
}