
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWindOracleLibrary.Models;

[Table("PRODUCTS")]
public partial class Products
{
    [Column("PRODUCT_ID")]
    [Display(Name = "Id")]
    public int ProductId { get; set; }

    [Column("PRODUCT_NAME")]
    [Display(Name = "Name")]
    public string ProductName { get; set; }

    [Column("SUPPLIER_ID")]
    public int SupplierId { get; set; }

    [Column("CATEGORY_ID")]
    public int CategoryId { get; set; }

    [Column("QUANTITY_PER_UNIT")]
    public string QuantityPerUnit { get; set; }

    [Column("UNIT_PRICE")]
    public decimal UnitPrice { get; set; }

    [Column("UNITS_IN_STOCK")]
    public int UnitsInStock { get; set; }

    [Column("UNITS_ON_ORDER")]
    public int UnitsOnOrder { get; set; }

    [Column("REORDER_LEVEL")]
    public int ReorderLevel { get; set; }

    [Column("DISCONTINUED")]
    public string Discontinued { get; set; }

    public virtual Categories Categories { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual Suppliers Suppliers { get; set; }
}