
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace NorthWindOracleLibrary.Models;

[Table("SHIPPERS")]
public partial class Shippers
{
    [Column("SHIPPER_ID")]
    public int ShipperId { get; set; }

    [Column("COMPANY_NAME")]
    public string CompanyName { get; set; }

    [Column("PHONE")]
    public string Phone { get; set; }
    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}