
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeApp.Models;

[Table("CATEGORIES")]
public partial class Categories
{
    [Column("CATEGORY_ID")]
    public int CategoryId { get; set; }

    [Column("CATEGORY_NAME")]
    public string CategoryName { get; set; }

    [Column("DESCRIPTION")]
    public string Description { get; set; }

    [Column("PICTURE")]
    public string Photo { get; set; }

    /// <summary>
    /// Used in OracleWinFormsApp2024 project to
    /// read images from a local folder
    /// </summary>
    [NotMapped]
    public Image Picture { get; set; }

    public override string ToString() => CategoryName;

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();
}