
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeApp.Models;

[Table("CATEGORIES")]
public partial class Categories
{
    public int CATEGORY_ID { get; set; }

    public string CATEGORY_NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string PICTURE { get; set; }

    public virtual ICollection<Products> PRODUCTS { get; set; } = new List<Products>();
}