
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeApp.Models;

[Table("CUSTOMERS")]
public partial class Customers
{
    public int CUSTOMER_ID { get; set; }

    public string CUSTOMER_CODE { get; set; }

    public string COMPANY_NAME { get; set; }

    public string CONTACT_NAME { get; set; }

    public string CONTACT_TITLE { get; set; }

    public string ADDRESS { get; set; }

    public string CITY { get; set; }

    public string REGION { get; set; }

    public string POSTAL_CODE { get; set; }

    public string COUNTRY { get; set; }

    public string PHONE { get; set; }

    public string FAX { get; set; }

    public virtual ICollection<Orders> ORDERS { get; set; } = new List<Orders>();
}