
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeApp.Models;

[Table("ORDER_DETAILS")]
public partial class OrderDetails
{
    public int ORDER_ID { get; set; }

    public int PRODUCT_ID { get; set; }

    public decimal UNIT_PRICE { get; set; }

    public int QUANTITY { get; set; }

    public decimal DISCOUNT { get; set; }

    public virtual Orders ORDER { get; set; }

    public virtual Products PRODUCT { get; set; }
}