
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeApp.Models;

[Table("ORDERS")]
public partial class Orders
{
    public int ORDER_ID { get; set; }

    public int CUSTOMER_ID { get; set; }

    public int EMPLOYEE_ID { get; set; }

    public DateTime ORDER_DATE { get; set; }

    public DateTime? REQUIRED_DATE { get; set; }

    public DateTime? SHIPPED_DATE { get; set; }

    public int? SHIP_VIA { get; set; }

    public decimal? FREIGHT { get; set; }

    public string SHIP_NAME { get; set; }

    public string SHIP_ADDRESS { get; set; }

    public string SHIP_CITY { get; set; }

    public string SHIP_REGION { get; set; }

    public string SHIP_POSTAL_CODE { get; set; }

    public string SHIP_COUNTRY { get; set; }

    public virtual Customers CUSTOMER { get; set; }

    public virtual Employees EMPLOYEE { get; set; }

    public virtual ICollection<OrderDetails> ORDER_DETAILS { get; set; } = new List<OrderDetails>();

    public virtual Shippers SHIP_VIANavigation { get; set; }
}