// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PracticeApp.Models;

namespace PracticeApp.Data.Configurations;

public partial class CategoriesConfiguration : IEntityTypeConfiguration<Categories>
{
    public void Configure(EntityTypeBuilder<Categories> entity)
    {
        entity.HasKey(e => e.CategoryId);

        entity.HasIndex(e => e.CategoryName, "UIDX_CATEGORY_NAME").IsUnique();

        entity.Property(e => e.CategoryId)
            .HasPrecision(9)
            .ValueGeneratedNever();
        entity.Property(e => e.CategoryName)
            .IsRequired()
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.Description)
            .HasMaxLength(2000)
            .IsUnicode(false);
        entity.Property(e => e.Photo)
            .HasMaxLength(255)
            .IsUnicode(false);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Categories> entity);
}