// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PracticeApp.Models;

namespace PracticeApp.Data.Configurations;

public partial class CustomersConfiguration : IEntityTypeConfiguration<Customers>
{
    public void Configure(EntityTypeBuilder<Customers> entity)
    {
        entity.HasKey(e => e.CUSTOMER_ID);

        entity.HasIndex(e => e.CITY, "IDX_CUSTOMERS_CITY");

        entity.HasIndex(e => e.COMPANY_NAME, "IDX_CUSTOMERS_COMPANY_NAME");

        entity.HasIndex(e => e.POSTAL_CODE, "IDX_CUSTOMERS_POSTAL_CODE");

        entity.HasIndex(e => e.REGION, "IDX_CUSTOMERS_REGION");

        entity.HasIndex(e => e.CUSTOMER_CODE, "UIDX_CUSTOMERS_CODE").IsUnique();

        entity.Property(e => e.CUSTOMER_ID)
            .HasPrecision(9)
            .ValueGeneratedNever();
        entity.Property(e => e.ADDRESS)
            .HasMaxLength(60)
            .IsUnicode(false);
        entity.Property(e => e.CITY)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.COMPANY_NAME)
            .IsRequired()
            .HasMaxLength(40)
            .IsUnicode(false);
        entity.Property(e => e.CONTACT_NAME)
            .HasMaxLength(30)
            .IsUnicode(false);
        entity.Property(e => e.CONTACT_TITLE)
            .HasMaxLength(30)
            .IsUnicode(false);
        entity.Property(e => e.COUNTRY)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.CUSTOMER_CODE)
            .IsRequired()
            .HasMaxLength(5)
            .IsUnicode(false);
        entity.Property(e => e.FAX)
            .HasMaxLength(24)
            .IsUnicode(false);
        entity.Property(e => e.PHONE)
            .HasMaxLength(24)
            .IsUnicode(false);
        entity.Property(e => e.POSTAL_CODE)
            .HasMaxLength(10)
            .IsUnicode(false);
        entity.Property(e => e.REGION)
            .HasMaxLength(15)
            .IsUnicode(false);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Customers> entity);
}