
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PracticeApp.Data;
using PracticeApp.Models;
using System;
using System.Collections.Generic;

namespace PracticeApp.Data.Configurations;

public partial class EmployeesConfiguration : IEntityTypeConfiguration<Employees>
{
    public void Configure(EntityTypeBuilder<Employees> entity)
    {
        entity.HasKey(e => e.EmployeeId);

        entity.HasIndex(e => e.LastName, "IDX_EMPLOYEES_LASTNAME");

        entity.HasIndex(e => e.PostalCode, "IDX_EMPLOYEES_POSTAL_CODE");

        entity.Property(e => e.EmployeeId)
            .HasPrecision(9)
            .ValueGeneratedNever();
        entity.Property(e => e.Address)
            .HasMaxLength(60)
            .IsUnicode(false);
        entity.Property(e => e.BirthDate).HasColumnType("DATE");
        entity.Property(e => e.City)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.Country)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.Extension)
            .HasMaxLength(4)
            .IsUnicode(false);
        entity.Property(e => e.FirstName)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false);
        entity.Property(e => e.HireDate).HasColumnType("DATE");
        entity.Property(e => e.HomePhone)
            .HasMaxLength(24)
            .IsUnicode(false);
        entity.Property(e => e.LastName)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false);
        entity.Property(e => e.Notes)
            .HasMaxLength(2000)
            .IsUnicode(false);
        entity.Property(e => e.Photo)
            .HasMaxLength(255)
            .IsUnicode(false);
        entity.Property(e => e.PostalCode)
            .HasMaxLength(10)
            .IsUnicode(false);
        entity.Property(e => e.Region)
            .HasMaxLength(15)
            .IsUnicode(false);
        entity.Property(e => e.ReportsTo).HasPrecision(9);
        entity.Property(e => e.Title)
            .HasMaxLength(30)
            .IsUnicode(false);
        entity.Property(e => e.TitleOfCourtesy)
            .HasMaxLength(25)
            .IsUnicode(false);

        entity.HasOne(d => d.REPORTS_TONavigation).WithMany(p => p.InverseReportsToNavigation)
            .HasForeignKey(d => d.ReportsTo)
            .HasConstraintName("FK_REPORTS_TO");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Employees> entity);
}