
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PracticeApp.Data;
using PracticeApp.Models;
using System;
using System.Collections.Generic;

namespace PracticeApp.Data.Configurations
{
    public partial class OrderDetailsConfiguration : IEntityTypeConfiguration<OrderDetails>
    {
        public void Configure(EntityTypeBuilder<OrderDetails> entity)
        {
            entity.HasKey(e => new { e.ORDER_ID, e.PRODUCT_ID });

            entity.HasIndex(e => e.ORDER_ID, "IDX_ORDER_DETAILS_ORDER_ID");

            entity.HasIndex(e => e.PRODUCT_ID, "IDX_ORDER_DETAILS_PRODUCT_ID");

            entity.Property(e => e.ORDER_ID).HasPrecision(9);
            entity.Property(e => e.PRODUCT_ID).HasPrecision(9);
            entity.Property(e => e.DISCOUNT)
            .HasDefaultValueSql("0\n   ")
            .HasColumnType("NUMBER(4,2)");
            entity.Property(e => e.QUANTITY)
            .HasPrecision(9)
            .HasDefaultValueSql("1");
            entity.Property(e => e.UNIT_PRICE)
            .HasDefaultValueSql("0")
            .HasColumnType("NUMBER(10,2)");

            entity.HasOne(d => d.ORDER).WithMany(p => p.ORDER_DETAILS)
            .HasForeignKey(d => d.ORDER_ID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ORDER_ID");

            entity.HasOne(d => d.PRODUCT).WithMany(p => p.ORDER_DETAILS)
            .HasForeignKey(d => d.PRODUCT_ID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PRODUCT_ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderDetails> entity);
    }
}
