// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PracticeApp.Models;

namespace PracticeApp.Data.Configurations;

public partial class ShippersConfiguration : IEntityTypeConfiguration<Shippers>
{
    public void Configure(EntityTypeBuilder<Shippers> entity)
    {
        entity.HasKey(e => e.SHIPPER_ID);

        entity.Property(e => e.SHIPPER_ID)
            .HasPrecision(9)
            .ValueGeneratedNever();
        entity.Property(e => e.COMPANY_NAME)
            .IsRequired()
            .HasMaxLength(40)
            .IsUnicode(false);
        entity.Property(e => e.PHONE)
            .HasMaxLength(24)
            .IsUnicode(false);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Shippers> entity);
}