
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PracticeApp.Data;
using PracticeApp.Models;
using System;
using System.Collections.Generic;

namespace PracticeApp.Data.Configurations
{
    public partial class SuppliersConfiguration : IEntityTypeConfiguration<Suppliers>
    {
        public void Configure(EntityTypeBuilder<Suppliers> entity)
        {
            entity.HasKey(e => e.SupplierId);

            entity.HasIndex(e => e.CompanyName, "IDX_SUPPLIERS_COMPANY_NAME");

            entity.HasIndex(e => e.PostalCode, "IDX_SUPPLIERS_POSTAL_CODE");

            entity.Property(e => e.SupplierId)
            .HasPrecision(9)
            .ValueGeneratedNever();
            entity.Property(e => e.Address)
            .HasMaxLength(60)
            .IsUnicode(false);
            entity.Property(e => e.City)
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.CompanyName)
            .IsRequired()
            .HasMaxLength(40)
            .IsUnicode(false);
            entity.Property(e => e.ContactName)
            .HasMaxLength(30)
            .IsUnicode(false);
            entity.Property(e => e.ContactTitle)
            .HasMaxLength(30)
            .IsUnicode(false);
            entity.Property(e => e.Country)
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.FAX)
            .HasMaxLength(24)
            .IsUnicode(false);
            entity.Property(e => e.HomePage)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Phone)
            .HasMaxLength(24)
            .IsUnicode(false);
            entity.Property(e => e.PostalCode)
            .HasMaxLength(10)
            .IsUnicode(false);
            entity.Property(e => e.Region)
            .HasMaxLength(15)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Suppliers> entity);
    }
}
